spring:
  application:
    name: mcloud-msg
  #数据库配置
  datasource:
    url: jdbc:mysql://monkeyzi:3306/mcloud-quartz?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: guoguo
    password: gao1223fengguo
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      stat-view-servlet:
        # 默认true 内置监控页面首页/druid/index.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: root
        login-password: root
        # IP白名单 多个逗号分隔
        allow:
        # IP黑名单
        deny:
  #controller
  redis:
    host: 127.0.0.1
    password: 1223gao
    timeout: 5000ms


server:
  port: 8084
mcloud:
  redis-cache:
   redisCacheConfigs:
    - key: user
      second: 600
